name: local_file_transfer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  web_socket_channel: ^3.0.3

  network_info_plus: ^7.0.0
  connectivity_plus: ^7.0.0

  provider: ^6.1.5
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.14

  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.1
  image: ^4.7.2
  mime: ^2.0.0

  ffmpeg_kit_flutter_new: ^4.1.0

  flutter_svg: ^2.2.3

  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - ios/
