name: local_file_transfer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  local_websocket: ^0.0.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  file_picker: ^10.3.8
  mime: ^2.0.0
  crypto: ^3.0.7
  open_file: ^3.5.11
  url_launcher: ^6.3.2

  provider: ^6.1.5
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^10.0.0

  network_info_plus: ^7.0.0
  connectivity_plus: ^7.0.0

  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
